<?php

namespace Database\Seeders;
use App\Models\Comuna;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ComunaSeeder extends Seeder
{
    public function run(): void
    {
        Comuna::insert([

            ['nombre'=>'SOCIALISTA EL PANAL 2021', 'parroquia_id'=>'10111' ],
            ['nombre'=>'GUAL Y ESPAÑA', 'parroquia_id'=>'10111' ],
            ['nombre'=>'SOCIALISTA SIM N BOLIVAR', 'parroquia_id'=>'10111' ],
            ['nombre'=>'GIGANTE CACIQUE TIUNA', 'parroquia_id'=>'10111' ],
            ['nombre'=>'CIRCUITO 13 DE ABRIL CHAVEZ PUEBLO REBELDE', 'parroquia_id'=>'10111' ],
            ['nombre'=>'CIRCUITO CHAVEZ COMANDANTE INVICTO', 'parroquia_id'=>'10111' ],
            ['nombre'=>'MAGALLANES II', 'parroquia_id'=>'10111' ],
            ['nombre'=>'CIRCUITO INDEPENDENCIA REVOLUCIONARIA', 'parroquia_id'=>'10111' ],
            ['nombre'=>'CIRCUITO ISAIAS MEDINA ANGARITA', 'parroquia_id'=>'10111' ],
            ['nombre'=>'CIRCUITO LA CAÑADA', 'parroquia_id'=>'10111' ],
            ['nombre'=>'CIRCUITO VANGUARDIA DE LA REVOLUCION', 'parroquia_id'=>'10111' ],
            ['nombre'=>'FE SOCIALISTA', 'parroquia_id'=>'10111' ],
            ['nombre'=>'SOCIALISTA RAUL GARCIA', 'parroquia_id'=>'10111' ],
            ['nombre'=>'JUAN 23', 'parroquia_id'=>'10111' ],
            ['nombre'=>'SOCIALISTA COMANDANTE HUGO CHAVEZ', 'parroquia_id'=>'10111' ],
            ['nombre'=>'SOCIALISTA SIERRA MAESTRA', 'parroquia_id'=>'10111' ],
            ['nombre'=>'SOCIALISTA BICENTENARIA SANTA TERESA', 'parroquia_id'=>'10101' ],
            ['nombre'=>'MIRAFLORES ALTAGRACIA', 'parroquia_id'=>'10101' ],
            ['nombre'=>'CIRCUITO LA VEGUITA', 'parroquia_id'=>'10101' ],
            ['nombre'=>'CIRCUITO SIMON BOLIVAR ALTAGRACIA', 'parroquia_id'=>'10101' ],
            ['nombre'=>'CIRCUITO MIRAFLORES HUGO CHAVEZ', 'parroquia_id'=>'10101' ],
            ['nombre'=>'CIRCUITO COMUNAL 3 ALTAGRACIA', 'parroquia_id'=>'10101' ],
            ['nombre'=>'SOCIALISTA ZONA NORTE ALTAGRACIA', 'parroquia_id'=>'10101' ],
            ['nombre'=>'EL PARAISO DE MAISANTA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'VICTORIA SOCIALISTA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'JOSE FELIX RIBAS', 'parroquia_id'=>'10112' ],
            ['nombre'=>'BICENTENARIA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'LUISA CACERES DE ARISMENDI 4F', 'parroquia_id'=>'10112' ],
            ['nombre'=>'BOLIVAR VIVE', 'parroquia_id'=>'10112' ],
            ['nombre'=>'17 VOCES EZEQUIEL ZAMORA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'COMUNA SOCIALISTA ANTONIO JOSE DE SUCRE', 'parroquia_id'=>'10112' ],
            ['nombre'=>'BOLIVAR Y RODRIGUEZ', 'parroquia_id'=>'10112' ],
            ['nombre'=>'JUANA RAMIREZ LA AVANZADORA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'CIRCUITO 8VA ESTRELLA SOCIALISTA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'CIRCUITO UNIDAD LUCHA BATALLA Y VICTORIA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'CIRCUITO COMUNAL EMPRENDER LA PATRIA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'UNIDAD Y FUERZA BOLIVARIANA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'SOCIALISTA CIRCULO DE LUCHA CHAVEZ VIVE', 'parroquia_id'=>'10112' ],
            ['nombre'=>'UN PASO AL FRENTE', 'parroquia_id'=>'10112' ],
            ['nombre'=>'COMUNA SOCIALISTA LUCHADORES DEL COMANDANTE SUPREMO', 'parroquia_id'=>'10112' ],
            ['nombre'=>'MAMERA SOCIALISTA REVOLUCIONARIA Y CHAVISTA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'TIERRA LIBRE NEGRA MATEA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'RENACER EN REVOLUCION', 'parroquia_id'=>'10112' ],
            ['nombre'=>'SOCIALISTA CARAPITA INSURGENTE', 'parroquia_id'=>'10112' ],
            ['nombre'=>'CHILIYING DEL MANGUITO', 'parroquia_id'=>'10112' ],
            ['nombre'=>'EL MANANTIAL Y CEIBA SOCIALISTA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'BICENTENARIO 4 F', 'parroquia_id'=>'10112' ],
            ['nombre'=>'SOCIALISTA PRODUCTIVA CACIQUE SOROCAIMA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'RENACE CHAVEZ CON FUERZA Y VICTORIA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'COMUNA AGRICOLA MONTE SINAI', 'parroquia_id'=>'10112' ],
            ['nombre'=>'PEDRO CAMEJO 2020', 'parroquia_id'=>'10112' ],
            ['nombre'=>'COMUNA EN HONOR A NUESTRO COMANDANTE SUPREMO', 'parroquia_id'=>'10112' ],
            ['nombre'=>'SOCIALISTA UNA SOLA FUERZA', 'parroquia_id'=>'10112' ],
            ['nombre'=>'JUNTOS VENCEREMOS', 'parroquia_id'=>'10112' ],
            ['nombre'=>'CAMINOS DE INDEPENDENCIA', 'parroquia_id'=>'10102' ],
            ['nombre'=>'CIRCUITO CANDELARIA NORTE', 'parroquia_id'=>'10102' ],
            ['nombre'=>'CIRCUITO CHEILA SILVA', 'parroquia_id'=>'10102' ],
            ['nombre'=>'CIRCUITO CIRCUITO 2', 'parroquia_id'=>'10102' ],
            ['nombre'=>'SARRIA REBELDE', 'parroquia_id'=>'10102' ],
            ['nombre'=>'LUCHADORES POR EL BUEN VIVIR', 'parroquia_id'=>'10117' ],
            ['nombre'=>'URBANISMO BRISAS DEL ALBA', 'parroquia_id'=>'10117' ],
            ['nombre'=>'PODER REVOLUCIONARIO 2018', 'parroquia_id'=>'10117' ],
            ['nombre'=>'SOCIALISTA EL DESPERTAR DEL ONOTO', 'parroquia_id'=>'10117' ],
            ['nombre'=>'VAMOS GENTE DE MI TIERRA', 'parroquia_id'=>'10117' ],
            ['nombre'=>'SOCIALISTA ALIANZA REVOLUCIONARIA', 'parroquia_id'=>'10117' ],
            ['nombre'=>'POR AQUI PASO BOLIVAR', 'parroquia_id'=>'10117' ],
            ['nombre'=>'SOCIALISTA INDIO CARICUAO', 'parroquia_id'=>'10117' ],
            ['nombre'=>'ECOSOCIALISTA UNIDOS VENCEREMOS', 'parroquia_id'=>'10117' ],
            ['nombre'=>'LOS GIGANTES DE LA PATRIA', 'parroquia_id'=>'10117' ],
            ['nombre'=>'ECOLOGICA SOCIALISTA LA HACIENDA UD5 UD6', 'parroquia_id'=>'10117' ],
            ['nombre'=>'ECOSOCIALISTA CHAVEZ SIEMPRE CHAVEZ', 'parroquia_id'=>'10117' ],
            ['nombre'=>'ECOSOCIALISTA TERRAZAS DE CARICUAO', 'parroquia_id'=>'10117' ],
            ['nombre'=>'LANCEROS DE LA VICTORIA', 'parroquia_id'=>'10117' ],
            ['nombre'=>'AGROAMBIENTAL POR LA DEFENSA DE LA BIODIVERSIDAD EL SOL DE LA PAZ', 'parroquia_id'=>'10117' ],
            ['nombre'=>'SOCIALISTA ZOOLOGICO UD3 Y CC2', 'parroquia_id'=>'10117' ],
            ['nombre'=>'ECO-SOCIALISTA GOLPE DE TIMON UD-5', 'parroquia_id'=>'10117' ],
            ['nombre'=>'CACIQUE GUAICAIPURO 2021', 'parroquia_id'=>'10103' ],
            ['nombre'=>'CACIQUE CARAPAICA', 'parroquia_id'=>'10103' ],
            ['nombre'=>'HERENCIA HISTORICA CATEDRAL', 'parroquia_id'=>'10103' ],
            ['nombre'=>'CIRCUITO COMUNAL SUEÑOS DEL COMANDANTE', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO COMUNAL HEROINAS DE LA PATRIA', 'parroquia_id'=>'10119' ],
            ['nombre'=>'EZEQUIEL ZAMORA', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO CASCO VIEJO', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO COMUNA SINDULFA ALVARADO', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO COMUNA ARMANDO REVERON', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO COMUNA CORAZON ZAMORANO DE MI PATRIA', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO COMUNA FELIPE ANTONIO ACOSTA', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO COMUNA GRAN COLOMBIA SOCIALISTA', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO COMUNA GUERREROS DE LAS MAYAS', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO COMUNA TURMERITO', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO DARIO VIVAS', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO VENEZUELA INDESTRUCTIBLE', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO VICTORIO MENDEZ', 'parroquia_id'=>'10119' ],
            ['nombre'=>'CIRCUITO URBANISMO', 'parroquia_id'=>'10119' ],
            ['nombre'=>'HEROINAS DE LA PATRIA', 'parroquia_id'=>'10119' ],
            ['nombre'=>'LOS BOSQUES', 'parroquia_id'=>'10119' ],
            ['nombre'=>'PROPUESTA DE CIRCUITO: LOS GUAMALES', 'parroquia_id'=>'10119' ],
            ['nombre'=>'LANCEROS DE GUAICAIPURO', 'parroquia_id'=>'10119' ],
            ['nombre'=>'EL SUEÑO DE UN GIGANTE', 'parroquia_id'=>'10119' ],
            ['nombre'=>'FORJANDO LOS SUEÑOS DE EZEQUIEL ZAMORA', 'parroquia_id'=>'10119' ],
            ['nombre'=>'EL ARAÑERO DE SABANETA DEL SIGLO XXI', 'parroquia_id'=>'10119' ],
            ['nombre'=>'ALI PRIMERA SIGLO XXI', 'parroquia_id'=>'10119' ],
            ['nombre'=>'LA LUZ DEL GIGANTE CHAVEZ', 'parroquia_id'=>'10119' ],
            ['nombre'=>'EL JUNQUITO ECOSOCIALISTA', 'parroquia_id'=>'10118' ],
            ['nombre'=>'LOS SUEÑOS DEL COMANDANTE ETERNO', 'parroquia_id'=>'10118' ],
            ['nombre'=>'INDEPENDENCIA DE MI PATRIA', 'parroquia_id'=>'10118' ],
            ['nombre'=>'RESISTENCIA INDIGENA', 'parroquia_id'=>'10118' ],
            ['nombre'=>'LA REVOLUCION DEL JUNQUITO', 'parroquia_id'=>'10118' ],
            ['nombre'=>'BOLIVAR CHAVEZ EL JUNQUITO', 'parroquia_id'=>'10118' ],
            ['nombre'=>'ERA BICENTENARIA', 'parroquia_id'=>'10118' ],
            ['nombre'=>'A EJE 4', 'parroquia_id'=>'10122' ],
            ['nombre'=>'CIRCUITO EL PETROLEO SAN MIGUEL', 'parroquia_id'=>'10122' ],
            ['nombre'=>'CIRCUITO EL SOL NACIENTE DE VENEZUELA EJE 2', 'parroquia_id'=>'10122' ],
            ['nombre'=>'CIRCUITO LA ESPADA DE BOLIVAR EJE 6', 'parroquia_id'=>'10122' ],
            ['nombre'=>'CIRCUITO LOS SUEÑOS DE CHAVEZ EJE 3', 'parroquia_id'=>'10122' ],
            ['nombre'=>'CIRCUITO RESPLANDOR DEL ALBA EJE 1', 'parroquia_id'=>'10122' ],
            ['nombre'=>'TERRAZAS DE LA QUEBRADITA', 'parroquia_id'=>'10122' ],
            ['nombre'=>'URBANISMO LA PAZ', 'parroquia_id'=>'10122' ],
            ['nombre'=>'BASE MISIONES MARISCAL SUCRE', 'parroquia_id'=>'10122' ],
            ['nombre'=>'COMUNA EN CONSTRUCCION BANDERA DE PAZ', 'parroquia_id'=>'10122' ],
            ['nombre'=>'SOBERANIA Y LIBERTAD', 'parroquia_id'=>'10122' ],
            ['nombre'=>'CIRCUITO CONGRESO DE ANGOSTURA', 'parroquia_id'=>'10113' ],
            ['nombre'=>'CIRCUITO ARTILLEROS DE CHAVEZ', 'parroquia_id'=>'10113' ],
            ['nombre'=>'CIRCUITO NEGRO LUIS VILLAFANIA', 'parroquia_id'=>'10113' ],
            ['nombre'=>'CIRCUITO SARRIA 1 SOLA A GOLPE DE TIMON', 'parroquia_id'=>'10113' ],
            ['nombre'=>'EJE 3 EL RECREO', 'parroquia_id'=>'10113' ],
            ['nombre'=>'AMALIVACA', 'parroquia_id'=>'10113' ],
            ['nombre'=>'APONWAO', 'parroquia_id'=>'10113' ],
            ['nombre'=>'HUGO CHAVEZ FRIAS', 'parroquia_id'=>'10114' ],
            ['nombre'=>'CIRCUITO LAS MALVINAS EN REVOLUCION', 'parroquia_id'=>'10114' ],
            ['nombre'=>'CIRCUITO LONGARAY', 'parroquia_id'=>'10114' ],
            ['nombre'=>'CIRCUITO LOS JARDINES', 'parroquia_id'=>'10114' ],
            ['nombre'=>'CIRCUITO VAMOS CON CHAYMA', 'parroquia_id'=>'10114' ],
            ['nombre'=>'CIRCUITO ZONA RESIDENCIAL SAN ANDRES', 'parroquia_id'=>'10114' ],
            ['nombre'=>'PUEBLO UNIDO EN REBELION', 'parroquia_id'=>'10114' ],
            ['nombre'=>'VALLE DULCE', 'parroquia_id'=>'10114' ],
            ['nombre'=>'HUGO CHAVEZ EL 70', 'parroquia_id'=>'10114' ],
            ['nombre'=>'TIERRA DE MUJERESY HOMBRES LIBRES', 'parroquia_id'=>'10114' ],
            ['nombre'=>'MANUEL EZEQUIEL BRUZUAL', 'parroquia_id'=>'10114' ],
            ['nombre'=>'SOCIALISTA LA PATRIA DE BOLIVAR II', 'parroquia_id'=>'10114' ],
            ['nombre'=>'RENACER DE VISTA ALEGRE', 'parroquia_id'=>'10114' ],
            ['nombre'=>'LA CEIBITA SOMOS TODOS', 'parroquia_id'=>'10114' ],
            ['nombre'=>'TAMARINDO EN REVOLUCION', 'parroquia_id'=>'10114' ],
            ['nombre'=>'ECOSOCIALISTA COMANDANTE', 'parroquia_id'=>'10114' ],
            ['nombre'=>'REVOLUCIONARIA SOCIALISTA SAN ANTONIO DE PADUA', 'parroquia_id'=>'10114' ],
            ['nombre'=>'VALLE FUERTE CAÑICITO', 'parroquia_id'=>'10114' ],
            ['nombre'=>'VENEZUELA PATRIA MIA', 'parroquia_id'=>'10114' ],
            ['nombre'=>'SOCIALISTA EL LEGADO DE UN GIGANTE', 'parroquia_id'=>'10114' ],
            ['nombre'=>'SOCIALISTA APACUANA', 'parroquia_id'=>'10114' ],
            ['nombre'=>'SAN ANDRES EN VICTORIA', 'parroquia_id'=>'10114' ],
            ['nombre'=>'SOCIALISTA LIBERTADORES DE SAN ANDRES', 'parroquia_id'=>'10114' ],
            ['nombre'=>'SOCIALISTA EZEQUIEL ZAMORA DEL VALLE', 'parroquia_id'=>'10114' ],
            ['nombre'=>'CIRCUITO BRISAS DE NIÑO JESUS', 'parroquia_id'=>'10104' ],
            ['nombre'=>'CIRCUITO CALIDAD DE VIDA VICTORIOSA', 'parroquia_id'=>'10104' ],
            ['nombre'=>'CIRCUITO JOSE GREGORIO HERNANDEZ', 'parroquia_id'=>'10104' ],
            ['nombre'=>'CIRCUITO PUEBLO REBELDE DE LIDICE', 'parroquia_id'=>'10104' ],
            ['nombre'=>'CIRCUITO SOCIALISTA BICENTENARIA MAISANTA', 'parroquia_id'=>'10104' ],
            ['nombre'=>'CIRCUITO COMUNAL INDIA APACUANA', 'parroquia_id'=>'10104' ],
            ['nombre'=>'SOCIALISTA DE LIBERTADORES', 'parroquia_id'=>'10104' ],
            ['nombre'=>'ESTA TIERRA ES NUESTRA', 'parroquia_id'=>'10104' ],
            ['nombre'=>'SOCIALISTA ALTOS DE LIDICE', 'parroquia_id'=>'10104' ],
            ['nombre'=>'POLVORIN UNIDO EN BATALLA VICTORIOSA', 'parroquia_id'=>'10104' ],
            ['nombre'=>'CACICA URQUIA LA PASTORA', 'parroquia_id'=>'10104' ],
            ['nombre'=>'AL SUR DE LA PASTORA', 'parroquia_id'=>'10104' ],
            ['nombre'=>'8 RAICES DE MECEDORES', 'parroquia_id'=>'10104' ],
            ['nombre'=>'FUERZA OBRERA DE LIDICE', 'parroquia_id'=>'10104' ],
            ['nombre'=>'LA RESISTENCIA HEROICA DE LIDICE', 'parroquia_id'=>'10104' ],
            ['nombre'=>'CIRCUITO GUERRERO Y GUERRERA DE LOS OJOS DE AGUA', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO GUILLERMO GARCIA PONCE', 'parroquia_id'=>'10115' ],
            ['nombre'=>'HIJOS DE BOLIVAR LA VEGA', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO HOYADA LA LADERA', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO JUAN VIVE SULIAR', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO LA MONTAÑITA', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO MONTALBAN 1 Y 2', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO RENACER DE HUGO CHAVEZ', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO TERRAZAS', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO TUMBITAS LAS AMAPOLAS', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO URB. HUGO CHAVEZ', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO VALLE ALEGRE', 'parroquia_id'=>'10115' ],
            ['nombre'=>'CIRCUITO VISTA HERMOSA SOCIALISTA', 'parroquia_id'=>'10115' ],
            ['nombre'=>'OSCAR ARNULFO ROMERO', 'parroquia_id'=>'10115' ],
            ['nombre'=>'EL TRIUNFO DEL LIBERTADOR II', 'parroquia_id'=>'10115' ],
            ['nombre'=>'EXITO COMUNITARIO SOCIALISTA', 'parroquia_id'=>'10115' ],
            ['nombre'=>'SOCIALISTA PUEBLO VICTORIOSO DEL CARMEN', 'parroquia_id'=>'10115' ],
            ['nombre'=>'RENACER DE BOLIVAR', 'parroquia_id'=>'10115' ],
            ['nombre'=>'LA HUELLA DE CH VEZ', 'parroquia_id'=>'10115' ],
            ['nombre'=>'HUGO SALAS', 'parroquia_id'=>'10115' ],
            ['nombre'=>'LA VEGUITA', 'parroquia_id'=>'10116' ],
            ['nombre'=>'CIRCUITO LEGADO DE CHAVEZ', 'parroquia_id'=>'10116' ],
            ['nombre'=>'CIRCUITO COMUNAL POR AHORA Y PARA SIEMPRE', 'parroquia_id'=>'10116' ],
            ['nombre'=>'CIRCUITO GIGANTE DE AMERICA', 'parroquia_id'=>'10116' ],
            ['nombre'=>'SOCIALISTA JORGE RODRIGUEZ PADRE', 'parroquia_id'=>'10116' ],
            ['nombre'=>'MACARAO GOLPE DE TIMON', 'parroquia_id'=>'10116' ],
            ['nombre'=>'LA OCTAVA ESTRELLA', 'parroquia_id'=>'10116' ],
            ['nombre'=>'POR AMOR Y LEALTAD A CHAVEZ', 'parroquia_id'=>'10116' ],
            ['nombre'=>'SUEÑOS Y PENSAMIENTOS DE CHAVEZ', 'parroquia_id'=>'10116' ],
            ['nombre'=>'CAMINO HACIA LA VICTORIA', 'parroquia_id'=>'10116' ],
            ['nombre'=>'CIRCUITO ESTACION DEL METRO CABLE SAN AGUSTIN', 'parroquia_id'=>'10105' ],
            ['nombre'=>'PARQUE CENTRAL', 'parroquia_id'=>'10105' ],
            ['nombre'=>'SAN AGUSTIN INVICTA CON MADURO', 'parroquia_id'=>'10105' ],
            ['nombre'=>'MATEA BOLIVAR 2021', 'parroquia_id'=>'10105' ],
            ['nombre'=>'ALEIDA HERNANDEZ', 'parroquia_id'=>'10105' ],
            ['nombre'=>'ZAMORA RENACE EN EL ALBA', 'parroquia_id'=>'10105' ],
            ['nombre'=>'BATALLA CARABOBO 200', 'parroquia_id'=>'10105' ],
            ['nombre'=>'CIRCUITO PROPUESTA DE CIRCUITO COMUNAL 1', 'parroquia_id'=>'10121' ],
            ['nombre'=>'GRAN CACIQUE PARAMACONI', 'parroquia_id'=>'10121' ],
            ['nombre'=>'CIRCUITO MARIA MATILDE LIENDO LA TITA', 'parroquia_id'=>'10106' ],
            ['nombre'=>'CIRCUITO SABANA DE LOS ÑARAULI', 'parroquia_id'=>'10106' ],
            ['nombre'=>'CIRCUITO YULIMAR ROJAS', 'parroquia_id'=>'10106' ],
            ['nombre'=>'GERARDO LOPEZ MUJICA COMANDANTE ENRIQUE', 'parroquia_id'=>'10106' ],
            ['nombre'=>'WARAIRA REPANO DE SAN JOSE', 'parroquia_id'=>'10106' ],
            ['nombre'=>'CIRCUITO SIMON BOLIVAR EL VALLE', 'parroquia_id'=>'10107' ],
            ['nombre'=>'CIRCUITO SAN JUAN BAUTISTA', 'parroquia_id'=>'10107' ],
            ['nombre'=>'CIRCUITO RESISTENCIA BOLIVARIANA', 'parroquia_id'=>'10107' ],
            ['nombre'=>'CIRCUITO FRANCISCO DE MIRANDA', 'parroquia_id'=>'10107' ],
            ['nombre'=>'CIRCUITO CASCO CENTRAL DOS ROSAS', 'parroquia_id'=>'10107' ],
            ['nombre'=>'CIRCUITO COMUNA BOLIVAR Y CHAVEZ', 'parroquia_id'=>'10107' ],
            ['nombre'=>'CIRCUITO MATERNIDAD MARIA CONCEPCION PALACIO', 'parroquia_id'=>'10107' ],
            ['nombre'=>'CIRCUITO OCTAVA ESTRELLA DE LA REVOLUCION', 'parroquia_id'=>'10107' ],
            ['nombre'=>'ANA KARINA ROTE', 'parroquia_id'=>'10107' ],
            ['nombre'=>'FORTALEZA Y DIGNIDAD DE UN PUEBLO PATRIOTA', 'parroquia_id'=>'10107' ],
            ['nombre'=>'ARQUITECTO CARLOS RAUL VILLANUEVA', 'parroquia_id'=>'10107' ],
            ['nombre'=>'AQUILES NAZOA', 'parroquia_id'=>'10107' ],
            ['nombre'=>'URQUIA', 'parroquia_id'=>'10107' ],
            ['nombre'=>'VOCES REVOLUCIONARIAS SIN FRONTERAS', 'parroquia_id'=>'10107' ],
            ['nombre'=>'EL SUEÑO DE HUGO CHAVEZ', 'parroquia_id'=>'10107' ],
            ['nombre'=>'CIRCUITO PROPONER CIRCUITO COMUNAL 2', 'parroquia_id'=>'10120' ],
            ['nombre'=>'CIRCUITO PROPONER CIRCUITO COMUNAL 3', 'parroquia_id'=>'10120' ],
            ['nombre'=>'GIGANTE CACIQUE TIUNA', 'parroquia_id'=>'10120' ],
            ['nombre'=>'CIRCUITO VENCEDORES DEL SUR', 'parroquia_id'=>'10108' ],
            ['nombre'=>'CIRCUITO LUCHADORES DEL PRADO', 'parroquia_id'=>'10108' ],
            ['nombre'=>'CIRCUITO MAO TSE TUNG', 'parroquia_id'=>'10108' ],
            ['nombre'=>'CIRCUITO 5 RAICES LUCHADORAS', 'parroquia_id'=>'10108' ],
            ['nombre'=>'CRISTO BOLIVAR Y CHAVEZ', 'parroquia_id'=>'10108' ],
            ['nombre'=>'ESTRELLAS DEL SUR', 'parroquia_id'=>'10108' ],
            ['nombre'=>'EL DESPERTAR DE LA COTA 905', 'parroquia_id'=>'10108' ],
            ['nombre'=>'COMANDANTE MIRABAL', 'parroquia_id'=>'10108' ],
            ['nombre'=>'PRIMERO DE MAYO UNIDO', 'parroquia_id'=>'10108' ],
            ['nombre'=>'5 DE MARZO COMANDANTE ETERNO', 'parroquia_id'=>'10108' ],
            ['nombre'=>'VILLA ZOILA', 'parroquia_id'=>'10108' ],
            ['nombre'=>'COMISION PROMOTORA COMUNA COMANDANTE HUGO CHAVEZ', 'parroquia_id'=>'10108' ],
            ['nombre'=>'JORGE RODRIGUEZ PADRE', 'parroquia_id'=>'10108' ],
            ['nombre'=>'SOCIALISTA CRUZ VILLEGAS', 'parroquia_id'=>'10108' ],
            ['nombre'=>'MANUELITA SAENZ 2021', 'parroquia_id'=>'10108' ],
            ['nombre'=>'GRAN CACIQUE GUAICAIPURO GDUAPOTORU WAIKAEPURU', 'parroquia_id'=>'10108' ],
            ['nombre'=>'MARTIN MOSQUEDA', 'parroquia_id'=>'10109' ],
            ['nombre'=>'BOLIVARIANA Y REVOLUCIONARIA LA SILSA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO ALI PRIMERA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO AVENIDA SUCRE', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO BIMA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO BLANDIN EN VICTORIA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO GUARACARUMBO', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO INDIO CARACAS', 'parroquia_id'=>'10110' ],
            ['nombre'=>'EJE 5', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO LA ESPERANZA DE CASALTA (EJE 16)', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO LA ESPERANZA DE CASALTA CACIQUE (EJE 15)', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO LOMA GRANDE (EJE 11)', 'parroquia_id'=>'10110' ],
            ['nombre'=>'MAGALLANES III', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO LUCHADORES DE LA PATRIA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO LUCHADORES DEL NAZARENO', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO MANUEL VERDU (EJE 14)', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO MI HIJO NICOLAS', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO MOROCHITO RODRIGUEZ (EJE 14)', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO UNIDOS POR EL AMPARO', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO UNION BOLIVARIANA IMA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'MAGALLANES I', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CIRCUITO VIENTOS De LIBERTAD', 'parroquia_id'=>'10110' ],
            ['nombre'=>'LOMAS DE URDANETA CIRCUITO 1', 'parroquia_id'=>'10110' ],
            ['nombre'=>'LOMAS DE URDANETA CIRCUITO 2', 'parroquia_id'=>'10110' ],
            ['nombre'=>'DESPERTAR DE UN PUEBLO CON CHAVEZ', 'parroquia_id'=>'10110' ],
            ['nombre'=>'PLAN DE MANZANO CHAVEZ POR SIEMPRE', 'parroquia_id'=>'10110' ],
            ['nombre'=>'RENACER DEL PUEBLO CON CHAVEZ', 'parroquia_id'=>'10110' ],
            ['nombre'=>'SOCIALISTA LOS FRAILES', 'parroquia_id'=>'10110' ],
            ['nombre'=>'AGROECOLOGICA TURISTICA EL GRAN TOPO', 'parroquia_id'=>'10110' ],
            ['nombre'=>'SOCIALISTA CIUDAD CARIBIA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'EL RENACER Y EL FUTURO DE BOLIVAR Y CHAVEZ', 'parroquia_id'=>'10110' ],
            ['nombre'=>'SOCIALISTA FABRICIO OJEDA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'GUAICAMACUTO BICENTENARIO LIMON NUEVO DIA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'COMUNA SOCIALISTA EXPLOSION DEL PODER POPULAR', 'parroquia_id'=>'10110' ],
            ['nombre'=>'LA VISION DE CHAVEZ', 'parroquia_id'=>'10110' ],
            ['nombre'=>'LOS FLORES EN REVOLUCION', 'parroquia_id'=>'10110' ],
            ['nombre'=>'FABRICIO VIVE', 'parroquia_id'=>'10110' ],
            ['nombre'=>'ECO SOCIALISTA LAGUNA KATIA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'SOCIALISTA UNIDOS POR VISTA AL MAR', 'parroquia_id'=>'10110' ],
            ['nombre'=>'REVOLUCIONARIA PEREZ BONALDE', 'parroquia_id'=>'10110' ],
            ['nombre'=>'ANTIMPERIALISTA LA LUCHA DE CHAVEZ CONTINUA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'GRAN COMUNA DE ALTAVISTA PROF PEREZ MENDEZ', 'parroquia_id'=>'10110' ],
            ['nombre'=>'BATALLA DE SANTA INES CASCO CENTRAL DE CATIA', 'parroquia_id'=>'10110' ],
            ['nombre'=>'BOLIVAR URDANETA Y CHAVEZ', 'parroquia_id'=>'10110' ],
            ['nombre'=>'COMUNA ECOAMBIENTALISTA EL TANQUE', 'parroquia_id'=>'10110' ],
            ['nombre'=>'GENERALISIMO FRANCISCO DE MIRANDA 2021', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CORAZON DE CHAVEZ', 'parroquia_id'=>'10110' ],
            ['nombre'=>'SOCIALISTA LA FELICIDAD DEL PUEBLO', 'parroquia_id'=>'10110' ],
            ['nombre'=>'WILFREDO ROCHE', 'parroquia_id'=>'10110' ],
            ['nombre'=>'REVOLUCIONARIA MAGALLANES', 'parroquia_id'=>'10110' ],
            ['nombre'=>'GUERREROS DE GUAICAIPURO', 'parroquia_id'=>'10110' ],
            ['nombre'=>'GRAN CACIQUE GUAICAIPURO', 'parroquia_id'=>'10110' ],
            ['nombre'=>'REVOLUCIONARIA Y COMBATIVA BOLIVAR Y SUCRE', 'parroquia_id'=>'10110' ],
            ['nombre'=>'CORAZON DE MI PATRIA', 'parroquia_id'=>'10110' ],
        ]);
    }
}
